# num1 = int(input("Enter num1 = "))
#num2 = int(input("Enter num2 = "))
#print(type(num1), type(num2))
# print(num1+num2)
# print(num1-num2)
# print(num1/num2)
#print(num1 > num2)
#print(num1 <= num2)
#print(num1 >= num2)
#print(num1 == num2)
#print(num1 != num2)
#print(not (num1 > num2))
#print(num1 > num2 or num1 == num2)
#print(num1 > num2 and num1 == num2)
# num1 += 1
# print(num1)
